-- Foto delle auto (Wikimedia Commons, licenze libere con attribuzione) e 12 nuove auto demo.
-- Le immagini demo sono servite dal frontend (frontend/public/auto/*.webp).
alter table auto add column immagine_url varchar(500);
alter table auto add column immagine_credito varchar(300);
alter table auto add column immagine_fonte varchar(500);
create index idx_auto_marca on auto (lower(marca));

update auto set immagine_url = '/auto/fiat-panda.webp', immagine_credito = 'Foto: Vauxford — CC BY-SA 4.0, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:2018_Fiat_Panda_Easy_1.2.jpg' where marca = 'Fiat' and modello = 'Panda 1.0 Hybrid';
update auto set immagine_url = '/auto/volkswagen-golf.webp', immagine_credito = 'Foto: Vauxford — CC BY-SA 4.0, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:2020_Volkswagen_Golf_Style_1.5_Front.jpg' where marca = 'Volkswagen' and modello = 'Golf 8 1.5 eTSI';
update auto set immagine_url = '/auto/toyota-yaris-cross.webp', immagine_credito = 'Foto: Alexander-93 — CC BY-SA 4.0, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:Toyota_Yaris_Cross_Hybrid_(XP210)_1X7A1846.jpg' where marca = 'Toyota' and modello = 'Yaris Cross';
update auto set immagine_url = '/auto/bmw-serie-3.webp', immagine_credito = 'Foto: Vauxford — CC BY-SA 4.0, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:2019_BMW_318d_SE_Automatic_2.0_Front.jpg' where marca = 'BMW' and modello = 'Serie 3 320d';
update auto set immagine_url = '/auto/renault-clio.webp', immagine_credito = 'Foto: M 93 — CC BY-SA 3.0 de, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:Renault_Clio_(V,_Facelift)_%E2%80%93_f_02092025.jpg' where marca = 'Renault' and modello = 'Clio TCe 90';
update auto set immagine_url = '/auto/tesla-model-3.webp', immagine_credito = 'Foto: Alexander-93 — CC BY-SA 4.0, via Wikimedia Commons', immagine_fonte = 'https://commons.wikimedia.org/wiki/File:Tesla_Model_3_(2023)_Autofr%C3%BChling_Ulm_IMG_9282.jpg' where marca = 'Tesla' and modello = 'Model 3 RWD';
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Peugeot', '208 PureTech 100 Allure', 2021, 33000, 'i-Cockpit 3D, navigatore, gomme nuove.' || chr(10) || 'Unico proprietario.', 15800.00, 13200.00, 'PUBBLICATA', '/auto/peugeot-208.webp', 'Foto: M 93 — CC BY-SA 3.0 de, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Peugeot_208_PureTech_130_EAT8_Allure_GT-Line_(II)_%E2%80%93_f_17102021.jpg', now() - interval '1 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Fiat', '500 1.0 Hybrid Dolcevita', 2021, 27000, 'Tetto panoramico, Apple CarPlay, ideale per la città.', 12900.00, 10600.00, 'PUBBLICATA', '/auto/fiat-500.webp', 'Foto: Ad Meskens — CC BY-SA 3.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Fiat_500_(2007)_02.JPG', now() - interval '2 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Audi', 'A3 Sedan 35 TFSI S tronic', 2021, 46000, 'Virtual cockpit, cerchi da 17", fari LED.', 27900.00, 24000.00, 'PUBBLICATA', '/auto/audi-a3.webp', 'Foto: Alexander Migl — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Audi_A3_8Y_Sedan_IMG_5936.jpg', now() - interval '3 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Ford', 'Puma 1.0 EcoBoost Hybrid Titanium', 2020, 52000, 'Mild hybrid 125 CV, MegaBox nel bagagliaio.', 17900.00, 15100.00, 'PUBBLICATA', '/auto/ford-puma.webp', 'Foto: Vauxford — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2020_Ford_Puma_Titanium_EcoBoost_Hybrid_1.0_Front.jpg', now() - interval '4 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Jeep', 'Renegade 1.6 Multijet Longitude', 2019, 78000, 'Diesel 120 CV, gancio traino, tagliandi Jeep.', 15500.00, 12800.00, 'PUBBLICATA', '/auto/jeep-renegade.webp', 'Foto: M 93 — CC BY-SA 3.0 de, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Jeep_Renegade_1.6_MultiJet_2WD_Longitude_%E2%80%93_Frontansicht,_9._November_2014,_D%C3%BCsseldorf.jpg', now() - interval '5 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Dacia', 'Duster TCe 130 Extreme', 2024, 12000, 'Nuovo modello, telecamera 360°, garanzia fino al 2027.', 21900.00, 19300.00, 'PUBBLICATA', '/auto/dacia-duster.webp', 'Foto: M 93 — CC BY-SA 3.0 de, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Dacia_Duster_TCe_130_Extreme_(III)_%E2%80%93_f_13102024.jpg', now() - interval '6 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Mercedes-Benz', 'Classe A 200 AMG Line', 2019, 64000, 'MBUX con doppio display, interni AMG.', 23500.00, 20100.00, 'PUBBLICATA', '/auto/mercedes-classe-a.webp', 'Foto: Vauxford — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2018_Mercedes-Benz_A200_AMG_Line_Premium_Automatic_1.3_Front.jpg', now() - interval '7 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Alfa Romeo', 'Giulia 2.2 Turbodiesel 160 CV Super', 2019, 92000, 'Cambio automatico 8 marce, sedili in pelle.', 22900.00, 19000.00, 'PUBBLICATA', '/auto/alfa-romeo-giulia.webp', 'Foto: Johannes Maximilian — GFDL 1.2, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Alfa_952_26.06.19_JM_(1)_(cropped).jpg', now() - interval '8 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Hyundai', 'Tucson 1.6 T-GDI HEV Xline', 2022, 38000, 'Full hybrid 230 CV, garanzia Hyundai 5 anni.', 28500.00, 25200.00, 'PUBBLICATA', '/auto/hyundai-tucson.webp', 'Foto: SsmIntrigue — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2022_Hyundai_Tucson_Preferred,_Front_Right,_05-24-2021.jpg', now() - interval '9 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Volkswagen', 'T-Roc 1.5 eTSI Style', 2025, 6000, 'Seconda generazione, praticamente nuova.', 33900.00, 30500.00, 'PUBBLICATA', '/auto/volkswagen-t-roc.webp', 'Foto: M 93 — CC BY-SA 3.0 de, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:VW_T-Roc_1.5_eTSI_Style_(II)_%E2%80%93_f_05052026.jpg', now() - interval '0 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Toyota', 'Corolla 1.8 Hybrid Active', 2020, 71000, 'Consumi reali 4,5 l/100 km, tagliandi Toyota.', 17400.00, 14600.00, 'PUBBLICATA', '/auto/toyota-corolla.webp', 'Foto: EurovisionNim — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2018_Toyota_Corolla_(MZEA12R)_Ascent_Sport_hatchback_(2018-11-02)_01.jpg', now() - interval '10 days', now());
insert into auto (marca, modello, anno, chilometri, descrizione, prezzo, prezzo_acquisto, stato, immagine_url, immagine_credito, immagine_fonte, created_at, updated_at) values ('Kia', 'Sportage 1.6 T-GDi HEV Style', 2025, 9000, 'Km 0 reali, garanzia Kia 7 anni.', 34500.00, 31000.00, 'PUBBLICATA', '/auto/kia-sportage.webp', 'Foto: LuvsMG481 — CC BY-SA 4.0, via Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:2025_Kia_Sportage_S_front_only.jpg', now() - interval '11 days', now());
